# Generated by Django 3.2.19 on 2024-09-26 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0002_auto_20240926_1155'),
        ('acoes', '0003_alter_acoes_acao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acoes',
            name='dispositivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispositivos.dispositivos'),
        ),
    ]
