# Generated by Django 3.2.19 on 2024-09-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivos',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dispositivos',
            name='devId',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
